[package]
name = "macros-impl"
version = "0.0.0"
edition = "2021"
rust-version = "1.74"
license = "MIT OR Apache-2.0"

[dependencies]
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["clone-impls", "extra-traits", "full", "parsing", "printing"] }
