image: docker.io/rust:slim-bookworm

services:
  - name: docker.io/groonga/pgroonga:latest-alpine-12-slim
    alias: postgres
  - name: docker.io/redis:7-alpine
    alias: redis

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
      when: never

cache:
  paths:
    - node_modules
    - /cache/cargo/registry/index
    - /cache/cargo/registry/cache
    - target/debug/deps
    - target/debug/build

stages:
  - test

variables:
  POSTGRES_DB: 'firefish_db'
  POSTGRES_USER: 'firefish'
  POSTGRES_PASSWORD: 'password'
  POSTGRES_HOST_AUTH_METHOD: 'trust'
  DEBIAN_FRONTEND: 'noninteractive'
  CARGO_PROFILE_DEV_OPT_LEVEL: '0'
  CARGO_PROFILE_DEV_LTO: 'off'
  CARGO_PROFILE_DEV_DEBUG: 'none'
  CARGO_HOME: '/cache/cargo'

default:
  before_script:
    - apt-get -y install curl
    - curl -fsSL 'https://deb.nodesource.com/setup_18.x' | sudo -E bash -
    - apt-get update && apt-get upgrade
    - apt-get install -y build-essential clang mold python3 perl nodejs postgresql-client
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - cp .config/ci.yml .config/default.yml
    - cp ci/cargo/config.toml "${CARGO_HOME}/config.toml"
    - export PGPASSWORD="${POSTGRES_PASSWORD}"
    - psql --host postgres --user "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" --command 'CREATE EXTENSION pgroonga'

build_and_cargo_unit_test:
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm run build:debug
    - pnpm run migrate
    - cargo test
