[workspace]
members = ["packages/backend-rs"]
resolver = "2"

[workspace.dependencies]
napi = { version = "2.16.2", default-features = false }
napi-derive = "2.16.2"
napi-build = "2.1.2"

async-trait = "0.1.79"
basen = "0.1.0"
cfg-if = "1.0.0"
chrono = "0.4.37"
cuid2 = "0.1.2"
jsonschema = "0.17.1"
once_cell = "1.19.0"
parse-display = "0.9.0"
pretty_assertions = "1.4.0"
rand = "0.8.5"
schemars = "0.8.16"
sea-orm = "0.12.15"
serde = "1.0.197"
serde_json = "1.0.115"
thiserror = "1.0.58"
tokio = "1.37.0"

[profile.release]
lto = true
