version: "3"

services:
  web:
    image: registry.firefish.dev/firefish/firefish:latest
    container_name: firefish_web
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    networks:
      - calcnet
#     - web
    environment:
      NODE_ENV: production
    volumes:
      - ./custom:/firefish/custom:ro
      - ./files:/firefish/files
      - ./.config:/firefish/.config:ro

  redis:
    restart: unless-stopped
    image: docker.io/redis:7.0-alpine
    container_name: firefish_redis
    networks:
      - calcnet
    volumes:
      - ./redis:/data

  db:
    restart: unless-stopped
    image: docker.io/groonga/pgroonga:latest-alpine-16-slim
    container_name: firefish_db
    networks:
      - calcnet
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  calcnet:
  #  web:
  #    external:
  #      name: web
