version: "3"

services:
  web:
    image: docker.io/node:21-slim
    container_name: firefish_web
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "3030:3030"
    networks:
      - firefishnet
    environment:
      # Currently bug in the development env and it cannot run.
      NODE_ENV: production
      PGPASSWORD: password
      URL: http://localhost:3030
    volumes:
      - ./firefish:/firefish:rw
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:rw
    entrypoint: /docker-entrypoint.sh

  redis:
    restart: unless-stopped
    image: docker.io/redis:7.0-alpine
    container_name: firefish_redis
    networks:
      - firefishnet
    ports:
      - "26379:6379"
    volumes:
      - ./redis:/data

  db:
    restart: unless-stopped
    image: docker.io/groonga/pgroonga:latest-alpine-15-slim
    container_name: firefish_db
    networks:
      - firefishnet
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=firefish"
      - "POSTGRES_DB=firefish_db"
    ports:
      - "25432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  firefishnet:
